services:
  - type: web
    name: numina-server
    env: node
    region: oregon
    buildCommand: npm ci && ls -la src/ && node --check src/server.js
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 