services:
  - type: web
    name: aether-server
    env: node
    region: oregon
    plan: starter
    instanceCount: 1
    buildCommand: npm ci --production && node --check src/server-clean.js
    startCommand: node --max-old-space-size=256 --optimize-for-size src/server-clean.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: "--max-old-space-size=256 --optimize-for-size" 